### PR TITLE
Add GraphiQL support

### PR DESCRIPTION
**Pull request by mastertinner**
I took the template from https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js and go-ified it.

@sogko and others: Please let me know what you think.

If you like it, I'll add the necessary tests and make the code cleaner.

I've had some trouble adding `ResultString` and `VariablesString`. I would be glad about some advice about where to get them.

### CODE REVIEW

**Comment by yookoala** [comment]
This seems nice. Please do merge.

**Comment by mastertinner** [comment]
I resolved the problems mentioned above and added tests so I think this can be merged.

**Comment by mastertinner** [comment]
I resolved the problems mentioned above and added tests so I think this can be merged now.

**Comment by mastertinner** [comment]
@sogko, can you please comment or merge?

**Comment by klud1** [comment]
where can the ui be reached? i'm going to `/graphiql` but i get a 404. thanks in advance

**Comment by mastertinner** [comment]
@klud1, it's at the same URL where your graphql endpoint is. If you reach it with a browser, it will return the GraphiQL GUI.

**Comment by klud1** [comment]
Alright, it's working! Thanks, awesome work!

**Comment by klud1** [comment]
Alright, it's working! Thanks, awesome work! Hope this gets merged asap so i don't have to tweak my build process in order to get these changes.

**Comment by chris-ramon** [comment]
LGTM :+1:  — this is really awesome, thanks a lot @mastertinner! :ship:

**Comment by mastertinner** [comment]
Thanks for merging, @chris-ramon! Could you create a new release `0.2.0` which contains GraphiQL?

**Comment by chris-ramon** [comment]
> Thanks for merging, @chris-ramon! Could you create a new release 0.2.0 which contains GraphiQL?

Sure thing!, https://github.com/graphql-go/handler/releases/tag/v0.2.0

**Comment by mastertinner** [comment]
Nice! Thanks, @chris-ramon!

**Pull request merged**
